export const SITE_CONFIG = {
  brandName: "Nexus",
  companyName: "Nexus Integrated Distribution System",
  version: "v1.0.0",
  currencySymbol: "Rp",
  numberLocale: "id-ID",
  dateFormat: "dd/MM/yyyy",
  timeFormat: "HH:mm",
  assets: {
    loginImage: "/images/company-logo.jpg",
  }
}

export type Language = 'en' | 'id'

export const SITE_CONTENT = {
  en: {
    // Login Page
    LOGIN_TITLE: "NIDS System",
    LOGIN_SUBTITLE: "Enter your credentials to access the Nexus",
    LOGIN_ERROR_PENDING: "Your account is pending approval from the administrator.",
    LOGIN_ERROR_INVALID: "Invalid username or password.",
    LABEL_USERNAME: "Username",
    PLACEHOLDER_USERNAME: "admin",
    LABEL_PASSWORD: "Password",
    PLACEHOLDER_PASSWORD: "••••••••",
    BUTTON_LOGIN: "Sign In",
    LINK_SIGNUP: "Sign Up",
    TEXT_NO_ACCOUNT: "Don't have an account?",
    COPYRIGHT: "© 2026 Nexus Integrated Distribution System",

    // Signup Page
    SIGNUP_TITLE: "Create Account",
    SIGNUP_SUBTITLE: "Join the Nexus, approval required.",
    SIGNUP_SUCCESS_TITLE: "Registration Successful!",
    SIGNUP_SUCCESS_MSG: "Your account is pending boss approval.",
    LABEL_FULL_NAME: "Full Name",
    LABEL_EMAIL: "Email Address",
    LABEL_PHONE: "Phone Number",
    PLACEHOLDER_PHONE: "+62...",
    TOOLTIP_LANG: "Switch Language",
    BUTTON_SIGNUP: "Request Access",
    BUTTON_SIGNUP_LOADING: "Creating Account...",
    LINK_LOGIN: "Sign In",
    LINK_BACK_LOGIN: "Back to Login",
    LINK_RETURN_LOGIN: "Return to Login",
    TEXT_HAS_ACCOUNT: "Already have an account?",

    // Navigation / Titles
    MENU_DASHBOARD: "Dashboard",
    MENU_COMPANIES: "Companies",
    MENU_PRODUCTS: "Products",
    MENU_QUOTES: "Quotes",
    MENU_ORDERS: "Orders",
    MENU_SHIPMENTS: "Shipments",
    MENU_FUNDERS: "Funders",
    MENU_TRANSACTION: "Transaction",
    MENU_DEPOSIT: "Deposit",
    MENU_QUOTATION: "Quotation",
    MENU_SALES_ORDER: "Sales Order",
    MENU_DELIVERY_ORDER: "Delivery Order",
    MENU_VEHICLES: "Vehicles",
    MENU_INVOICE: "Invoice",
    MENU_PAYMENTS: "Payments",
    MENU_SETTINGS: "Settings",
    MENU_REPORTS_INVENTORY: "Inventory Report",
    MENU_REPORTS_DEPOSIT: "Deposit Report",
    MENU_REPORTS_QUOTATION: "Quotation Report",
    MENU_REPORTS_SO: "Sales Order Report",
    MENU_REPORTS_INVOICE: "Invoice Report",
    MENU_REPORTS_PAYMENTS: "Payment Report",
    MENU_REPORTS_PROFIT_LOSS: "Profit & Loss",

    // Quotation Module
    LABEL_QUOTATION_NUMBER: "Quotation Number",
    LABEL_QUOTATION_DATE: "Quotation Date",
    LABEL_EXPIRY_DATE: "Expiry Date",
    LABEL_VALIDITY_DAYS: "Validity Days",
    LABEL_MIN_ORDER: "Min. Order",
    LABEL_STATUS: "Status",
    LABEL_CONTENT: "Quotation Content",
    LABEL_NOTE: "Quotation Note",
    LABEL_TERMS: "Terms and Conditions",
    LABEL_CLOSING: "Closing Remarks",
    LABEL_SHRINKAGE_TOLERANCE: "Shrinkage Tolerance (%)",
    LABEL_TRANSPORT_COST: "Transport Cost",
    LABEL_DELIVERY_ADDRESS: "Delivery Address",
    LABEL_MARGIN: "Margin",
    LABEL_TOTAL_PRICE: "Total Price",
    LABEL_PRICE_PER_L: "Price per L",
    LABEL_DELIVERY_PER_L: "Delivery per L",
    LABEL_BANK_ACCOUNTS: "Bank Accounts",
    LABEL_DISCOUNTS: "Discounts",
    LABEL_DISCOUNT_NAME: "Discount Name",
    LABEL_DISCOUNT_VALUE: "Value (%)",
    LABEL_DISCOUNT_TERMS: "Discount Terms",
    LABEL_TERM_OF_PAYMENT: "Term of Payment",
    LABEL_TAX_VAT: "Enable Tax (VAT)",
    LABEL_TAX_RATE: "Tax Rate (%)",
    LABEL_TAXES: "Taxes",
    LABEL_SUBTOTAL: "Subtotal",
    LABEL_DELIVERY_TOTAL: "Delivery Total",
    LABEL_GRAND_TOTAL: "Grand Total",
    LABEL_TOTAL_DEPOSITS: "Total Deposits",
    LABEL_TOTAL_QUOTATIONS: "Total Quotations",
    LABEL_DRAFT_QUOTATIONS: "Draft Quotations",
    LABEL_SENT_QUOTATIONS: "Sent Quotations",
    LABEL_ALMOST_EXPIRED: "Almost Expired",
    LABEL_TOTAL_SOS: "Total Sales Orders",
    LABEL_TOTAL_INVOICES: "Total Invoices",
    LABEL_TOTAL_PAYMENTS: "Total Payments",
    LABEL_TOTAL_AMOUNT: "Total Amount",
    LABEL_TOTAL_VOLUME: "Total Volume",
    LABEL_TOTAL_CUSTOMERS: "Total Customers",
    LABEL_TOTAL_SUPPLIERS: "Total Suppliers",
    LABEL_TOTAL_TRANSPORTERS: "Total Transporters",
    LABEL_TOTAL_VEHICLES: "Total Vehicles",
    LABEL_TOTAL_USERS: "Total Users",
    LABEL_ACTIVE_VEHICLES: "Active Vehicles",
    LABEL_TOTAL_DOS: "Total Delivery Orders",
    LABEL_TOTAL_VALUE: "Total Value",
    LABEL_ACCEPTED: "Accepted",
    LABEL_COMPLETED: "Completed",
    LABEL_DELIVERED: "Delivered",
    LABEL_VERIFIED: "Verified",
    LABEL_IN_TRANSIT: "In Transit",
    LABEL_LOGISTICS: "Logistics",
    LABEL_WAREHOUSE_ID: "Warehouse ID",
    LABEL_AVG_COST: "Avg Cost",
    LABEL_INVENTORY_VALUE: "Inventory Value",
    LABEL_ACTIVE_WAREHOUSES: "Active Warehouses",
    LABEL_PENDING_AMOUNT: "Pending Amount",
    LABEL_PAID_AMOUNT: "Paid Amount",
    LABEL_FROM_DATE: "From Date",
    LABEL_TO_DATE: "To Date",
    LABEL_OPTIONAL: "Optional",
    LABEL_AUTO_GENERATED: "[Auto Generated]",

    BUTTON_NEW_QUOTATION: "New Quotation",
    BUTTON_EDIT_QUOTATION: "Edit Quotation",
    BUTTON_ADD_DISCOUNT: "Add Discount",
    BUTTON_SAVE_QUOTATION: "Save Quotation",

    MSG_QUOTATION_SAVED: "Quotation saved successfully.",
    MSG_QUOTATION_DELETED: "Quotation removed.",
    MSG_QUOTATION_STATUS_UPDATED: "Status updated.",
    MSG_DELETE_CONFIRM: "Are you sure you want to delete this?",
    MSG_EXPIRY_INFO: "Expiry is calculated based on Quotation Date.",

    // Deposit Module
    LABEL_DEPOSIT_NUMBER: "Deposit Number",
    LABEL_DEPOSIT_DATE: "Deposit Date",
    LABEL_PAYMENT_METHOD: "Payment Method",
    LABEL_AMOUNT: "Amount",
    LABEL_REMAINING: "Rem",
    BUTTON_NEW_DEPOSIT: "New Deposit",
    BUTTON_SAVE_DEPOSIT: "Save Deposit",
    MSG_DEPOSIT_SAVED: "Deposit saved successfully.",
    MSG_DEPOSIT_DELETED: "Deposit removed.",
    MSG_DEPOSIT_STATUS_UPDATED: "Deposit status [%data%] updated.",

    // Sales Order Module
    LABEL_SO_NUMBER: "SO Number",
    LABEL_SO_DATE: "SO Date",
    LABEL_DELIVERY_DATE: "Delivery Date",
    LABEL_QUANTITY: "Quantity",
    LABEL_UNIT_PRICE: "Unit Price",
    BUTTON_NEW_SO: "New Sales Order",
    BUTTON_NEW_INVOICE: "New Invoice",
    BUTTON_RECORD_PAYMENT: "Record Payment",
    BUTTON_SAVE_SO: "Save Sales Order",
    MSG_SO_SAVED: "Sales Order saved successfully.",
    MSG_SO_DELETED: "Sales Order removed.",
    MSG_SO_STATUS_UPDATED: "Sales Order status updated.",

    // Delivery Order Module
    LABEL_DO_NUMBER: "DO Number",
    LABEL_DO_DATE: "DO Date",
    LABEL_SHIPMENT_DATE: "Shipment Date",
    LABEL_INVOICE_NUMBER: "Invoice Number",
    LABEL_ISSUE_DATE: "Issue Date",
    LABEL_DUE_DATE: "Due Date",
    LABEL_PAYMENT_NUMBER: "Payment Number",
    LABEL_PAYMENT_DATE: "Payment Date",
    LABEL_REFERENCE_NUMBER: "Reference Number",
    LABEL_LINK_TO_PO: "Link to PO",
    LABEL_TAX_INCLUDED: "Include Tax (PPN)",
    LABEL_TAX_AUTO_CALC: "Calculate tax automatically",
    LABEL_ENABLE_NOTE: "Enable Note",
    LABEL_INTERNAL_NOTE: "Internal Note",
    LABEL_DATES: "Dates",
    LABEL_AMOUNTS: "Amounts",
    LABEL_PAID: "Paid",
    LABEL_VERIFY: "Verify",
    LABEL_REJECT: "Reject",
    LABEL_DRIVER_NAME: "Driver Name",
    LABEL_VEHICLE_NUMBER: "Vehicle Number",
    LABEL_VEHICLE: "Vehicle",
    LABEL_LICENSE_NUMBER: "License Number",
    LABEL_VEHICLE_TYPE: "Vehicle Type",
    LABEL_TOTAL_CAPACITY: "Total Capacity",
    LABEL_CAPACITY: "Capacity",
    LABEL_COMPARTMENTS: "Compartments",
    LABEL_SEAL_NUMBER: "Seal Number",
    LABEL_COMPARTMENT_NUMBER: "Komp #",
    BUTTON_NEW_DO: "New Delivery Order",
    BUTTON_SAVE_DO: "Save Delivery Order",
    BUTTON_ADD_COMPARTMENT: "Add Compartment",
    MSG_DO_SAVED: "Delivery Order saved successfully.",
    MSG_DO_DELETED: "Delivery Order removed.",
    MSG_DO_STATUS_UPDATED: "Delivery Order status updated.",

    // Permission Messages
    MSG_ACCESS_DENIED: "Access Denied",
    MSG_NO_PERMISSION: "You do not have permission to view this page.",

    MENU_USERS: "Users",
    MENU_LOGOUT: "Logout",
    MENU_GROUP_MASTER: "Master Data",
    MENU_GROUP_REPORTS: "Reports",
    MENU_GROUP_SYSTEM: "System",
    MENU_SHOWCASE: "UI Showcase",

    TITLE_COMPANIES: "Companies",
    TITLE_PRODUCTS: "Products",
    TITLE_FUNDERS: "Funders",

    TITLE_ADD_COMPANY: "Add Company",
    TITLE_EDIT_COMPANY: "Edit Company",
    TITLE_ADD_PRODUCT: "Add Product",
    TITLE_EDIT_PRODUCT: "Edit Product",
    TITLE_ADD_FUNDER: "Add Funder",
    TITLE_EDIT_FUNDER: "Edit Funder",
    TITLE_DELETE: "Confirm Delete",

    DASHBOARD_TITLE: "Executive Dashboard",
    LABEL_TOTAL_REVENUE: "Total Revenue",
    LABEL_ACTIVE_COMPANIES: "Active",
    LABEL_TOTAL_PRODUCTS: "Total Products",
    LABEL_FROM_LAST_MONTH: "from last month",
    LABEL_NEW_THIS_MONTH: "new this month",
    LABEL_PRODUCTS_IN_STOCK: "Oil grades in stock",

    // Labels
    LABEL_NAME: "Name",
    LABEL_COMPANY_NAME: "Company Name",
    LABEL_PRODUCT_NAME: "Product Name",
    LABEL_SKU: "SKU",
    LABEL_TYPE: "Type",
    LABEL_CATEGORY: "Category",
    LABEL_UNIT: "Unit",
    LABEL_PRICE: "Price",
    LABEL_BASE_PRICE: "Base Price",
    LABEL_ACTIONS: "Actions",
    LABEL_CONTACT_PERSON: "Contact Person",
    LABEL_DESCRIPTION: "Description",
    LABEL_CITY: "City",
    LABEL_ADDRESS: "Address",
    LABEL_ADDRESS_LABEL: "Address Label",
    LABEL_NPWP: "NPWP (Tax ID)",
    LABEL_ID_NUMBER: "ID Number",
    LABEL_OTHER_INFO: "Other Info",
    LABEL_TYPE_CUSTOMER: "Customer",
    LABEL_TYPE_SUPPLIER: "Supplier",
    LABEL_TYPE_TRANSPORTER: "Transporter",
    LABEL_COMPANY_CONTACT_INFO: "Company Information",

    // General UI
    BUTTON_SAVE: "Save",
    BUTTON_CANCEL: "Cancel",
    BUTTON_ADD: "Add New",
    BUTTON_EDIT: "Edit",
    BUTTON_DELETE: "Delete",
    BUTTON_REFRESH: "Refresh",
    PLACEHOLDER_SEARCH: "Search...",
    PLACEHOLDER_SELECT_ADDRESS: "Select an address...",
    PLACEHOLDER_SELECT_TERM: "Select term...",
    PLACEHOLDER_ENTER_ADDRESS: "Enter delivery address...",
    PLACEHOLDER_SELECT_QUOTATION: "Select a quotation...",
    PLACEHOLDER_TOP: "e.g. COD, Net 30",
    PLACEHOLDER_EDITOR: "Start typing...",
    LOADING: "Loading...",
    NO_DATA: "No data found.",
    LABEL_ALL: "All",
    LABEL_SORT_BY: "Sort By",
    LABEL_THEN_BY: "",
    LABEL_ASCENDING: "A to Z (Ascending)",
    LABEL_DESCENDING: "Z to A (Descending)",
    BUTTON_ADD_LEVEL: "Add Level",
    BUTTON_DELETE_LEVEL: "Delete Level",
    TITLE_SORT_SETTINGS: "Sort Configuration",

    // Status & Notifications
    MSG_STATUS_UPDATED: "Status Updated",
    MSG_UPDATE_SUCCESS: "Update Successful",
    MSG_DELETE_SUCCESS: "Data %data% Successfully Deleted",
    MSG_UPDATE_FAILED: "Update Failed",
    MSG_SAVE_SUCCESS: "Saved Successfully",
    MSG_SAVE_FAILED: "Save Failed",
    MSG_DATA_FETCH_FAILED: "Data Fetch Failed",
    MSG_SESSION_EXPIRED: "Session Expired",
    MSG_RELOGIN: "Your session has expired. Please sign in again to continue.",
    LABEL_IS_ACTIVE: "Active",
    LABEL_IS_INACTIVE: "Inactive",
    MSG_PRODUCT_STATUS: "Product is now",
    MSG_COMPANY_STATUS: "Company is now",

    LABEL_LANGUAGE: "Language",
    LABEL_THEME: "Theme",
    LABEL_LIGHT: "Light",
    LABEL_DARK: "Dark",
    LABEL_SYSTEM: "System",
    LABEL_ACTIVE_FUNDERS: "Active Funders",
    // User Management
    TITLE_USER_MGMT: "User Management",
    TITLE_MANAGE_USER: "Manage User",
    LABEL_USER: "User",
    LABEL_PHONE_SHORT: "Phone",
    LABEL_ROLE: "Role",
    LABEL_APPROVED: "Approved",
    LABEL_PENDING: "Pending",
    LABEL_ACTIVE: "Active",
    LABEL_DEACTIVATED: "Deactivated",
    LABEL_MODULE: "Module",
    LABEL_GRANULAR_PERMS: "Granular Permissions",
    LABEL_ACC_APPROVAL: "Account Approval",
    DESC_ACC_APPROVAL: "Approve this user to give them access to the system.",
    BUTTON_APPROVE: "Approve User",
    BUTTON_REVOKE: "Revoke Approval",
    BUTTON_MANAGE: "Manage",

    // Validation Errors
    ERROR_INVALID_EMAIL: "Please enter a valid email address.",
    ERROR_PASSWORD_SHORT: "Password must be at least 6 characters.",
    ERROR_EMAIL_EXISTS: "This email address is already in use.",
    ERROR_USERNAME_EXISTS: "This username is already taken. Please try another one.",
    ERROR_PHONE_EXISTS: "This phone number is already registered.",
    ERROR_INFO_EXISTS: "An account with this information already exists.",
    ERROR_REG_RESTRICTED: "Registration is currently restricted. Please contact an admin.",
    ERROR_SUBMIT_FAILED: "Unable to submit request. Please check your information.",
    ERROR_UNEXPECTED: "An unexpected error occurred. Please try again.",
    ERROR_TIMEOUT: "Request timed out. Please check your connection and try again.",
    ERROR_VERIFY_STATUS: "Unable to verify account status.",

    // Additional Labels
    LABEL_NO_AUTH: "No Auth",
    LABEL_LAST_LOGIN: "Last Login",
    LABEL_USERNAME_FIELD: "Username",
    PLACEHOLDER_LOGIN_FALLBACK: "admin or email@example.com",

    // Reset Password / Forgot Password
    TITLE_RESET_PWD: "Reset Password",
    DESC_RESET_PWD: "Securely update your Nexus password.",
    TITLE_SETUP_ACC: "Account Setup",
    DESC_SETUP_ACC: "Complete your Nexus account activation.",
    LABEL_NEW_PASSWORD: "New Password",
    LABEL_CONFIRM_PASSWORD: "Confirm New Password",
    BUTTON_SET_NEW_PWD: "Set New Password",
    MSG_VERIFYING_TOKEN: "Verifying security token...",
    ERROR_EXPIRED_LINK: "This security link has expired. Please contact your administrator to revoke and re-approve your account access.",
    ERROR_INVALID_LINK: "Invalid security link. Please use the link provided in your email.",
    MSG_SECURITY_UPDATED: "Security Updated",
    MSG_RESET_LINK_SENT: "Security Link Dispatched",
    DESC_SECURITY_REDIRECT: "Your password has been set successfully. You are being redirected to the login page to sign in with your new credentials.",
    LINK_FORGOT_PWD: "Forgot password?",
    TITLE_FORGOT_PWD: "Reset Password",
    DESC_FORGOT_PWD: "Enter your email address and we'll send you a link to reset your password.",
    MSG_RESET_SENT: "If an account exists with this email, you will receive a password reset link shortly.",
    BUTTON_SEND_LINK: "Send Link",
    ERROR_PASSWORD_MISMATCH: "Passwords do not match. Please try again.",

    // Settings Page
    SETTINGS_TITLE: "Global Settings",
    SETTINGS_SUBTITLE: "Manage enterprise identities, dynamic tax rates, and core operational configurations.",
    SETTINGS_TAB_COMPANY: "Company Profile",
    SETTINGS_TAB_BANKS: "Bank Accounts",
    SETTINGS_TAB_PARAMETERS: "System Parameters",

    // Settings Form Company Profile
    SETTINGS_SEC_COMPANY: "Enterprise Identity Specifications",
    SETTINGS_LABEL_NPWP: "NPWP (Tax Number)",
    SETTINGS_LABEL_LOGO_URL: "Brand Logo URL",
    SETTINGS_LABEL_NPWP_ADDRESS: "NPWP Address",
    SETTINGS_LABEL_SHIPPING_ADDRESS: "Operational / Shipping Office Address",
    SETTINGS_PLACEHOLDER_NPWP_ADDRESS: "Official address registered in NPWP profile",
    SETTINGS_PLACEHOLDER_SHIPPING_ADDRESS: "Operational headquarters address",
    SETTINGS_BUTTON_SAVE_COMPANY: "Save Specifications",

    // Settings Bank Accounts
    SETTINGS_SEC_BANKS: "Relational Settlement Bank Accounts",
    SETTINGS_ADD_BANK_ACC: "Add Bank Account",
    SETTINGS_EDIT_BANK_ACC: "Modify Bank Account",
    SETTINGS_LABEL_BANK_NAME: "Bank Name",
    SETTINGS_LABEL_ACC_NUM: "Account Number",
    SETTINGS_LABEL_ACC_HOLDER: "Account Holder Name",
    SETTINGS_LABEL_BRANCH: "Branch Name",
    SETTINGS_PLACEHOLDER_BANK_NAME: "e.g. Bank Mandiri, BCA, Bank Rakyat Indonesia",
    SETTINGS_PLACEHOLDER_ACC_NUM: "e.g. 111231002319",
    SETTINGS_PLACEHOLDER_ACC_HOLDER: "e.g. PT Anugerah Buana Sriwijaya",
    SETTINGS_PLACEHOLDER_BRANCH: "e.g. Letkol Iskandar",

    // Settings Parameters
    SETTINGS_SEC_PARAMS: "Dynamic Operational Parameters",
    SETTINGS_BUTTON_SAVE_PARAMS: "Save Parameters",
    SETTINGS_ADD_PARAM: "Add Parameter",
    SETTINGS_LABEL_PARAM_KEY: "Parameter Key",
    SETTINGS_LABEL_PARAM_VALUE: "Parameter Value",
    SETTINGS_LABEL_PARAM_LABEL: "Parameter Label",
    SETTINGS_LABEL_PARAM_DESC: "Parameter Description",

    // Settings Email Routing
    SETTINGS_TAB_EMAILS: "Email Routing",
    SETTINGS_SEC_EMAILS: "Automated Email Routing (CC)",
    SETTINGS_BUTTON_SAVE_EMAILS: "Save Routing Rules",

    // Verification Portal
    VERIFY_TITLE: "Document Verification",
    VERIFY_SUBTITLE: "Securely verify the authenticity of Nexus documents.",
    VERIFY_LABEL_QUOTATION_NUMBER: "Quotation Number",
    VERIFY_PLACEHOLDER_QUOTATION_NUMBER: "e.g. QTN/2026/001",
    VERIFY_BUTTON_VERIFY: "Verify Document",
    VERIFY_BUTTON_DOWNLOADING: "Downloading...",
    VERIFY_SUCCESS_TITLE: "Authenticity Confirmed",
    VERIFY_SUCCESS_MSG: "This is an authentic document issued by PT Anugerah Buana Sriwijaya.",
    VERIFY_ERROR_TITLE: "Verification Failed",
    VERIFY_ERROR_MSG: "The quotation number does not match this record. Please check and try again.",
    VERIFY_ERROR_RATE_LIMIT: "Too many failed attempts. Please try again in a few minutes.",
    VERIFY_DOC_DETAILS: "Document Details",
    VERIFY_LABEL_COMPANY: "Company",
    VERIFY_LABEL_DATE: "Issue Date",
    VERIFY_LABEL_TOTAL: "Grand Total",
    VERIFY_BUTTON_DOWNLOAD_OFFICIAL: "Download Official PDF",
  },
  id: {
    // Login Page
    LOGIN_TITLE: "Sistem NIDS",
    LOGIN_SUBTITLE: "Masukkan kredensial Anda untuk mengakses Nexus",
    LOGIN_ERROR_PENDING: "Akun Anda sedang menunggu persetujuan dari administrator.",
    LOGIN_ERROR_INVALID: "Nama pengguna atau kata sandi salah.",
    LABEL_USERNAME: "Nama Pengguna",
    PLACEHOLDER_USERNAME: "admin",
    LABEL_PASSWORD: "Kata Sandi",
    PLACEHOLDER_PASSWORD: "••••••••",
    BUTTON_LOGIN: "Masuk",
    LINK_SIGNUP: "Daftar",
    TEXT_NO_ACCOUNT: "Belum punya akun?",
    COPYRIGHT: "© 2026 Nexus Integrated Distribution System",

    // Signup Page
    SIGNUP_TITLE: "Buat Akun",
    SIGNUP_SUBTITLE: "Masuk ke Nexus. Perlu persetujuan bos.",
    SIGNUP_SUCCESS_TITLE: "Pendaftaran Berhasil!",
    SIGNUP_SUCCESS_MSG: "Akun Anda sedang menunggu persetujuan bos.",
    LABEL_FULL_NAME: "Nama Lengkap",
    LABEL_EMAIL: "Alamat Email",
    LABEL_PHONE: "Nomor Telepon",
    PLACEHOLDER_PHONE: "081xxx...",
    TOOLTIP_LANG: "Ganti Bahasa",
    BUTTON_SIGNUP: "Ajukan Akses",
    BUTTON_SIGNUP_LOADING: "Membuat Akun...",
    LINK_LOGIN: "Masuk",
    LINK_BACK_LOGIN: "Kembali ke Masuk",
    LINK_RETURN_LOGIN: "Kembali ke Masuk",
    TEXT_HAS_ACCOUNT: "Sudah punya akun?",

    // Navigation / Titles
    MENU_DASHBOARD: "Dasboard",
    MENU_COMPANIES: "Perusahaan",
    MENU_PRODUCTS: "Produk",
    MENU_QUOTES: "Penawaran",
    MENU_ORDERS: "Pesanan",
    MENU_SHIPMENTS: "Pengiriman",
    MENU_FUNDERS: "Funder",
    MENU_TRANSACTION: "Transaksi",
    MENU_DEPOSIT: "Setoran",
    MENU_QUOTATION: "Penawaran",
    MENU_SALES_ORDER: "Pesanan Penjualan",
    MENU_DELIVERY_ORDER: "Surat Jalan",
    MENU_VEHICLES: "Kendaraan",
    MENU_INVOICE: "Faktur",
    MENU_PAYMENTS: "Pembayaran",
    MENU_SETTINGS: "Pengaturan",
    MENU_REPORTS_INVENTORY: "Laporan Inventaris",
    MENU_REPORTS_DEPOSIT: "Laporan Setoran",
    MENU_REPORTS_QUOTATION: "Laporan Penawaran",
    MENU_REPORTS_SO: "Laporan SO",
    MENU_REPORTS_INVOICE: "Laporan Faktur",
    MENU_REPORTS_PAYMENTS: "Laporan Pembayaran",
    MENU_REPORTS_PROFIT_LOSS: "Profit & Loss",

    // Quotation Module
    LABEL_QUOTATION_NUMBER: "Nomor Penawaran",
    LABEL_QUOTATION_DATE: "Tanggal Penawaran",
    LABEL_EXPIRY_DATE: "Tanggal Kedaluwarsa",
    LABEL_VALIDITY_DAYS: "Masa Berlaku (Hari)",
    LABEL_DAYS: "Day(s)",
    LABEL_MIN_ORDER: "Min. Pesanan",
    LABEL_STATUS: "Status",
    LABEL_CONTENT: "Isi Penawaran",
    LABEL_NOTE: "Catatan Penawaran",
    LABEL_TERMS: "Syarat dan Ketentuan",
    LABEL_CLOSING: "Kata Penutup",
    LABEL_SHRINKAGE_TOLERANCE: "Toleransi Susut (%)",
    LABEL_TRANSPORT_COST: "Biaya Transportasi",
    LABEL_DELIVERY_ADDRESS: "Alamat Pengiriman",
    LABEL_MARGIN: "Margin",
    LABEL_TOTAL_PRICE: "Total Harga",
    LABEL_PRICE_PER_L: "Harga per L",
    LABEL_DELIVERY_PER_L: "Pengiriman per L",
    LABEL_BANK_ACCOUNTS: "Rekening Bank",
    LABEL_DISCOUNTS: "Diskon",
    LABEL_DISCOUNT_NAME: "Nama Diskon",
    LABEL_DISCOUNT_VALUE: "Nilai (%)",
    LABEL_DISCOUNT_TERMS: "Ketentuan Diskon",

    LABEL_TERM_OF_PAYMENT: "Termin Pembayaran",
    LABEL_TAX_VAT: "Aktifkan Pajak (PPN)",
    LABEL_TAX_RATE: "Tarif Pajak (%)",
    LABEL_SUBTOTAL: "Subtotal",
    LABEL_DELIVERY_TOTAL: "Total Pengiriman",
    LABEL_GRAND_TOTAL: "Total Keseluruhan",
    LABEL_TAXES: "Pajak",
    LABEL_TOTAL_DEPOSITS: "Total Setoran",
    LABEL_TOTAL_QUOTATIONS: "Total Penawaran",
    LABEL_DRAFT_QUOTATIONS: "Penawaran Draft",
    LABEL_SENT_QUOTATIONS: "Penawaran Terkirim",
    LABEL_ALMOST_EXPIRED: "Hampir Kedaluwarsa",
    LABEL_TOTAL_SOS: "Total SO",
    LABEL_TOTAL_INVOICES: "Total Faktur",
    LABEL_TOTAL_PAYMENTS: "Total Pembayaran",
    LABEL_TOTAL_AMOUNT: "Total Jumlah",
    LABEL_TOTAL_VOLUME: "Total Volume",
    LABEL_TOTAL_CUSTOMERS: "Pelanggan",
    LABEL_TOTAL_SUPPLIERS: "Pemasok",
    LABEL_TOTAL_TRANSPORTERS: "Transporters",
    LABEL_TOTAL_VEHICLES: "Total Kendaraan",
    LABEL_TOTAL_USERS: "Total Pengguna",
    LABEL_ACTIVE_VEHICLES: "Kendaraan Aktif",
    LABEL_TOTAL_DOS: "Total Surat Jalan",
    LABEL_TOTAL_VALUE: "Total Nilai",
    LABEL_ACCEPTED: "Diterima",
    LABEL_COMPLETED: "Selesai",
    LABEL_DELIVERED: "Terkirim",
    LABEL_VERIFIED: "Terverifikasi",
    LABEL_IN_TRANSIT: "Dalam Perjalanan",
    LABEL_LOGISTICS: "Logistik",
    LABEL_WAREHOUSE_ID: "ID Gudang",
    LABEL_AVG_COST: "Harga Rata-rata",
    LABEL_INVENTORY_VALUE: "Nilai Inventaris",
    LABEL_ACTIVE_WAREHOUSES: "Gudang Aktif",
    LABEL_PENDING_AMOUNT: "Jumlah Tertunda",
    LABEL_PAID_AMOUNT: "Jumlah Dibayar",
    LABEL_FROM_DATE: "Dari Tanggal",
    LABEL_TO_DATE: "Sampai Tanggal",
    LABEL_OPTIONAL: "Opsional",
    LABEL_AUTO_GENERATED: "[Otomatis]",
    PLACEHOLDER_SELECT_QUOTATION: "Pilih penawaran...",
    PLACEHOLDER_TOP: "Contoh: COD, Net 30",

    BUTTON_NEW_QUOTATION: "Penawaran Baru",
    BUTTON_EDIT_QUOTATION: "Ubah Penawaran",
    BUTTON_ADD_DISCOUNT: "Tambah Diskon",
    BUTTON_SAVE_QUOTATION: "Simpan Penawaran",

    MSG_QUOTATION_SAVED: "Penawaran %data% berhasil disimpan.",
    MSG_QUOTATION_DELETED: "Penawaran berhasil dihapus.",
    MSG_QUOTATION_STATUS_UPDATED: "Status diperbarui.",
    MSG_DELETE_CONFIRM: "Apakah Anda yakin ingin menghapus ini?",
    MSG_EXPIRY_INFO: "Kedaluwarsa dihitung berdasarkan Tanggal Penawaran.",

    // Deposit Module
    LABEL_DEPOSIT_NUMBER: "Nomor Setoran",
    LABEL_DEPOSIT_DATE: "Tanggal Setoran",
    LABEL_PAYMENT_METHOD: "Metode Pembayaran",
    LABEL_AMOUNT: "Jumlah",
    LABEL_REMAINING: "Sisa",
    BUTTON_NEW_DEPOSIT: "Setoran Baru",
    BUTTON_SAVE_DEPOSIT: "Simpan Setoran",
    MSG_DEPOSIT_SAVED: "Setoran berhasil disimpan.",
    MSG_DEPOSIT_DELETED: "Setoran berhasil dihapus.",
    MSG_DEPOSIT_STATUS_UPDATED: "Status setoran [%data%] diperbarui.",

    // Sales Order Module
    LABEL_SO_NUMBER: "Nomor SO",
    LABEL_SO_DATE: "Tanggal SO",
    LABEL_DELIVERY_DATE: "Tanggal Pengiriman",
    LABEL_QUANTITY: "Kuantitas",
    LABEL_UNIT_PRICE: "Harga Satuan",
    BUTTON_NEW_SO: "SO Baru",
    BUTTON_NEW_INVOICE: "Faktur Baru",
    BUTTON_RECORD_PAYMENT: "Catat Pembayaran",
    BUTTON_SAVE_SO: "Simpan SO",
    MSG_SO_SAVED: "Pesanan Penjualan berhasil disimpan.",
    MSG_SO_DELETED: "Pesanan Penjualan berhasil dihapus.",
    MSG_SO_STATUS_UPDATED: "Status Pesanan Penjualan diperbarui.",

    // Delivery Order Module
    LABEL_DO_NUMBER: "Nomor DO",
    LABEL_DO_DATE: "Tanggal DO",
    LABEL_SHIPMENT_DATE: "Tanggal Pengiriman",
    LABEL_INVOICE_NUMBER: "Nomor Faktur",
    LABEL_ISSUE_DATE: "Tanggal Terbit",
    LABEL_DUE_DATE: "Jatuh Tempo",
    LABEL_PAYMENT_NUMBER: "Nomor Pembayaran",
    LABEL_PAYMENT_DATE: "Tanggal Pembayaran",
    LABEL_REFERENCE_NUMBER: "Nomor Referensi",
    LABEL_LINK_TO_PO: "Tautkan ke PO",
    LABEL_TAX_INCLUDED: "Termasuk Pajak (PPN)",
    LABEL_TAX_AUTO_CALC: "Hitung pajak otomatis",
    LABEL_ENABLE_NOTE: "Aktifkan Catatan",
    LABEL_INTERNAL_NOTE: "Catatan Internal",
    LABEL_DATES: "Tanggal",
    LABEL_AMOUNTS: "Jumlah",
    LABEL_PAID: "Dibayar",
    LABEL_VERIFY: "Verifikasi",
    LABEL_REJECT: "Tolak",
    LABEL_DRIVER_NAME: "Nama Sopir",
    LABEL_VEHICLE_NUMBER: "Nomor Kendaraan",
    LABEL_VEHICLE: "Kendaraan",
    LABEL_LICENSE_NUMBER: "Nomor Polisi",
    LABEL_VEHICLE_TYPE: "Tipe Kendaraan",
    LABEL_TOTAL_CAPACITY: "Total Kapasitas",
    LABEL_CAPACITY: "Kapasitas",
    LABEL_COMPARTMENTS: "Kompartemen",
    LABEL_SEAL_NUMBER: "Nomor Segel",
    LABEL_COMPARTMENT_NUMBER: "Komp #",
    BUTTON_NEW_DO: "DO Baru",
    BUTTON_SAVE_DO: "Simpan DO",
    BUTTON_ADD_COMPARTMENT: "Tambah Kompartemen",
    MSG_DO_SAVED: "Surat Jalan berhasil disimpan.",
    MSG_DO_DELETED: "Surat Jalan berhasil dihapus.",
    MSG_DO_STATUS_UPDATED: "Status Surat Jalan diperbarui.",

    // Permission Messages
    MSG_ACCESS_DENIED: "Akses Ditolak",
    MSG_NO_PERMISSION: "Anda tidak memiliki izin untuk melihat halaman ini.",

    MENU_USERS: "Pengguna",

    MENU_LOGOUT: "Keluar",
    MENU_GROUP_MASTER: "Data Master",
    MENU_GROUP_REPORTS: "Laporan",
    MENU_GROUP_SYSTEM: "Sistem",
    MENU_SHOWCASE: "Showcase UI",

    TITLE_COMPANIES: "Perusahaan",
    TITLE_PRODUCTS: "Produk",
    TITLE_FUNDERS: "Funders",
    LABEL_ACTIVE_FUNDERS: "Funders Aktif",
    TITLE_ADD_COMPANY: "Tambah Perusahaan",
    TITLE_EDIT_COMPANY: "Ubah Perusahaan",
    TITLE_ADD_PRODUCT: "Tambah Produk",
    TITLE_EDIT_PRODUCT: "Ubah Produk",
    TITLE_ADD_FUNDER: "Tambah Funder",
    TITLE_EDIT_FUNDER: "Ubah Funder",
    TITLE_DELETE: "Konfirmasi Delete",

    DASHBOARD_TITLE: "Dasbor Eksekutif",
    LABEL_TOTAL_REVENUE: "Total Pendapatan",
    LABEL_ACTIVE_COMPANIES: "Aktif",
    LABEL_TOTAL_PRODUCTS: "Total Produk",
    LABEL_FROM_LAST_MONTH: "dari bulan lalu",
    LABEL_NEW_THIS_MONTH: "baru bulan ini",
    LABEL_PRODUCTS_IN_STOCK: "Varian oli tersedia",

    // Labels
    LABEL_NAME: "Nama",
    LABEL_COMPANY_NAME: "Nama Perusahaan",
    LABEL_PRODUCT_NAME: "Nama Produk",
    LABEL_SKU: "SKU",
    LABEL_TYPE: "Tipe",
    LABEL_CATEGORY: "Kategori",
    LABEL_UNIT: "Satuan",
    LABEL_PRICE: "Harga",
    LABEL_BASE_PRICE: "Harga Dasar",
    LABEL_ACTIONS: "Aksi",
    LABEL_CONTACT_PERSON: "Kontak Person",
    LABEL_DESCRIPTION: "Deskripsi",
    LABEL_CITY: "Kota",
    LABEL_ADDRESS: "Alamat",
    LABEL_ADDRESS_LABEL: "Label Alamat",
    LABEL_NPWP: "NPWP",
    LABEL_ID_NUMBER: "Nomor KTP",
    LABEL_OTHER_INFO: "Info Lainnya",
    LABEL_TYPE_CUSTOMER: "Pelanggan",
    LABEL_TYPE_SUPPLIER: "Pemasok",
    LABEL_TYPE_TRANSPORTER: "Transporter",
    LABEL_COMPANY_CONTACT_INFO: "Informasi Perusahaan",

    // General UI
    BUTTON_SAVE: "Simpan",
    BUTTON_CANCEL: "Batal",
    BUTTON_ADD: "Tambah Baru",
    BUTTON_EDIT: "Ubah",
    BUTTON_DELETE: "Hapus",
    BUTTON_REFRESH: "Muat Ulang",
    PLACEHOLDER_SEARCH: "Cari...",
    PLACEHOLDER_SELECT_ADDRESS: "Pilih alamat...",
    PLACEHOLDER_SELECT_TERM: "Pilih termin...",
    PLACEHOLDER_ENTER_ADDRESS: "Masukkan alamat pengiriman...",
    PLACEHOLDER_EDITOR: "Mulai mengetik...",
    LOADING: "Memuat...",
    NO_DATA: "Data tidak ditemukan.",
    LABEL_ALL: "Semua",
    LABEL_SORT_BY: "Urutkan",
    LABEL_THEN_BY: "",
    LABEL_ASCENDING: "A ke Z (Meningkat)",
    LABEL_DESCENDING: "Z ke A (Menurun)",
    BUTTON_ADD_LEVEL: "Tambah Level",
    BUTTON_DELETE_LEVEL: "Hapus Level",
    TITLE_SORT_SETTINGS: "Konfigurasi Pengurutan",

    // Status & Notifications
    MSG_STATUS_UPDATED: "Status %data% Diperbarui",
    MSG_UPDATE_SUCCESS: "Edit Data %data% Berhasil",
    MSG_DELETE_SUCCESS: "Data %data% berhasil dihapus.",
    MSG_UPDATE_FAILED: "Edit Data %data% Gagal",
    MSG_SAVE_SUCCESS: "Simpan Data %data% Berhasil",
    MSG_SAVE_FAILED: "Simpan Data %data% Gagal",
    MSG_DATA_FETCH_FAILED: "Gagal Mengambil Data",
    MSG_SESSION_EXPIRED: "Sesi Berakhir",
    MSG_RELOGIN: "Sesi Anda telah berakhir. Silakan masuk kembali untuk melanjutkan.",
    LABEL_IS_ACTIVE: "Aktif",
    LABEL_IS_INACTIVE: "Nonaktif",
    MSG_PRODUCT_STATUS: "Produk sekarang",
    MSG_COMPANY_STATUS: "Perusahaan sekarang",

    LABEL_LANGUAGE: "Bahasa",
    LABEL_THEME: "Tema",
    LABEL_LIGHT: "Terang",
    LABEL_DARK: "Gelap",
    LABEL_SYSTEM: "Sistem",

    // User Management
    TITLE_USER_MGMT: "Manajemen Pengguna",
    TITLE_MANAGE_USER: "Kelola Pengguna",
    LABEL_USER: "Pengguna",
    LABEL_PHONE_SHORT: "Telepon",
    LABEL_ROLE: "Peran",
    LABEL_APPROVED: "Disetujui",
    LABEL_PENDING: "Tertunda",
    LABEL_ACTIVE: "Aktif",
    LABEL_DEACTIVATED: "Dinonaktifkan",
    LABEL_MODULE: "Modul",
    LABEL_GRANULAR_PERMS: "Izin Granular",
    LABEL_ACC_APPROVAL: "Persetujuan Akun",
    DESC_ACC_APPROVAL: "Setujui pengguna ini untuk memberi mereka akses ke sistem.",
    BUTTON_APPROVE: "Setujui Pengguna",
    BUTTON_REVOKE: "Cabut Persetujuan",
    BUTTON_MANAGE: "Kelola",

    // Validation Errors
    ERROR_INVALID_EMAIL: "Silakan masukkan alamat email yang valid.",
    ERROR_PASSWORD_SHORT: "Kata sandi harus minimal 6 karakter.",
    ERROR_EMAIL_EXISTS: "Alamat email ini sudah digunakan.",
    ERROR_USERNAME_EXISTS: "Nama pengguna ini sudah diambil. Silakan coba yang lain.",
    ERROR_PHONE_EXISTS: "Nomor telepon ini sudah terdaftar.",
    ERROR_INFO_EXISTS: "Akun dengan informasi ini sudah ada.",
    ERROR_REG_RESTRICTED: "Pendaftaran saat ini dibatasi. Silakan hubungi admin.",
    ERROR_SUBMIT_FAILED: "Tidak dapat mengajukan permintaan. Silakan periksa informasi Anda.",
    ERROR_UNEXPECTED: "Terjadi kesalahan yang tidak terduga. Silakan coba lagi.",
    ERROR_TIMEOUT: "Permintaan kehabisan waktu. Silakan periksa koneksi Anda dan coba lagi.",
    ERROR_VERIFY_STATUS: "Tidak dapat memverifikasi status akun.",

    // Additional Labels
    LABEL_NO_AUTH: "Belum Ada Akun",
    LABEL_LAST_LOGIN: "Login Terakhir",
    LABEL_USERNAME_FIELD: "Nama Pengguna",
    PLACEHOLDER_LOGIN_FALLBACK: "admin atau email@example.com",

    // Reset Password / Forgot Password
    TITLE_RESET_PWD: "Atur Ulang Kata Sandi",
    DESC_RESET_PWD: "Perbarui kata sandi Nexus Anda dengan aman.",
    TITLE_SETUP_ACC: "Pengaturan Akun",
    DESC_SETUP_ACC: "Selesaikan aktivasi akun Nexus Anda.",
    LABEL_NEW_PASSWORD: "Kata Sandi Baru",
    LABEL_CONFIRM_PASSWORD: "Konfirmasi Kata Sandi Baru",
    BUTTON_SET_NEW_PWD: "Atur Kata Sandi Baru",
    MSG_VERIFYING_TOKEN: "Memverifikasi token keamanan...",
    ERROR_EXPIRED_LINK: "Tautan keamanan ini telah kedaluwarsa. Silakan hubungi administrator Anda.",
    ERROR_INVALID_LINK: "Tautan keamanan tidak valid. Silakan gunakan tautan yang disediakan di email Anda.",
    MSG_SECURITY_UPDATED: "Keamanan Diperbarui",
    MSG_RESET_LINK_SENT: "Tautan Keamanan Dikirim",
    DESC_SECURITY_REDIRECT: "Kata sandi Anda telah berhasil diatur. Anda sedang dialihkan ke halaman login.",
    LINK_FORGOT_PWD: "Lupa kata sandi?",
    TITLE_FORGOT_PWD: "Atur Ulang Kata Sandi",
    DESC_FORGOT_PWD: "Masukkan alamat email Anda dan kami akan mengirimkan tautan untuk mengatur ulang kata sandi Anda.",
    MSG_RESET_SENT: "Jika akun dengan email ini ada, Anda akan segera menerima tautan atur ulang kata sandi.",
    BUTTON_SEND_LINK: "Kirim Tautan",
    ERROR_PASSWORD_MISMATCH: "Kata sandi tidak cocok. Silakan coba lagi.",

    // Settings Page
    SETTINGS_TITLE: "Pengaturan Global",
    SETTINGS_SUBTITLE: "Kelola identitas perusahaan, tarif pajak dinamis, dan konfigurasi operasional inti.",
    SETTINGS_TAB_COMPANY: "Profil Perusahaan",
    SETTINGS_TAB_BANKS: "Rekening Bank",
    SETTINGS_TAB_PARAMETERS: "Parameter Sistem",

    // Settings Form Company Profile
    SETTINGS_SEC_COMPANY: "Spesifikasi Identitas Perusahaan",
    SETTINGS_LABEL_NPWP: "NPWP (Nomor Pajak)",
    SETTINGS_LABEL_LOGO_URL: "URL Logo Brand",
    SETTINGS_LABEL_NPWP_ADDRESS: "Alamat NPWP",
    SETTINGS_LABEL_SHIPPING_ADDRESS: "Alamat Kantor Operasional / Pengiriman",
    SETTINGS_PLACEHOLDER_NPWP_ADDRESS: "Alamat resmi yang terdaftar di profil NPWP",
    SETTINGS_PLACEHOLDER_SHIPPING_ADDRESS: "Alamat kantor pusat operasional",
    SETTINGS_BUTTON_SAVE_COMPANY: "Simpan Spesifikasi",

    // Settings Bank Accounts
    SETTINGS_SEC_BANKS: "Rekening Bank Setelmen Relasional",
    SETTINGS_ADD_BANK_ACC: "Tambah Rekening Bank",
    SETTINGS_EDIT_BANK_ACC: "Ubah Rekening Bank",
    SETTINGS_LABEL_BANK_NAME: "Nama Bank",
    SETTINGS_LABEL_ACC_NUM: "Nomor Rekening",
    SETTINGS_LABEL_ACC_HOLDER: "Nama Pemilik Rekening",
    SETTINGS_LABEL_BRANCH: "Nama Cabang",
    SETTINGS_PLACEHOLDER_BANK_NAME: "misal: Bank Mandiri, BCA, Bank Rakyat Indonesia",
    SETTINGS_PLACEHOLDER_ACC_NUM: "misal: 111231002319",
    SETTINGS_PLACEHOLDER_ACC_HOLDER: "misal: PT Anugerah Buana Sriwijaya",
    SETTINGS_PLACEHOLDER_BRANCH: "misal: Letkol Iskandar",

    // Settings Parameters
    SETTINGS_SEC_PARAMS: "Parameter Operasional Dinamis",
    SETTINGS_BUTTON_SAVE_PARAMS: "Simpan Parameter",
    SETTINGS_ADD_PARAM: "Tambah Parameter",
    SETTINGS_LABEL_PARAM_KEY: "Kunci Parameter",
    SETTINGS_LABEL_PARAM_VALUE: "Nilai Parameter",
    SETTINGS_LABEL_PARAM_LABEL: "Label Parameter",
    SETTINGS_LABEL_PARAM_DESC: "Deskripsi Parameter",

    // Settings Email Routing
    SETTINGS_TAB_EMAILS: "Perutean Email",
    SETTINGS_SEC_EMAILS: "Perutean Email Otomatis (CC)",
    SETTINGS_BUTTON_SAVE_EMAILS: "Simpan Aturan Perutean",

    // Verification Portal
    VERIFY_TITLE: "Verifikasi Dokumen",
    VERIFY_SUBTITLE: "Verifikasi keaslian dokumen Nexus dengan aman.",
    VERIFY_LABEL_QUOTATION_NUMBER: "Nomor Penawaran",
    VERIFY_PLACEHOLDER_QUOTATION_NUMBER: "misal: QTN/2026/001",
    VERIFY_BUTTON_VERIFY: "Verifikasi Dokumen",
    VERIFY_BUTTON_DOWNLOADING: "Mengunduh...",
    VERIFY_SUCCESS_TITLE: "Keaslian Terkonfirmasi",
    VERIFY_SUCCESS_MSG: "Ini adalah dokumen asli yang diterbitkan oleh PT Anugerah Buana Sriwijaya.",
    VERIFY_ERROR_TITLE: "Verifikasi Gagal",
    VERIFY_ERROR_MSG: "Nomor penawaran tidak cocok dengan catatan ini. Silakan periksa dan coba lagi.",
    VERIFY_ERROR_RATE_LIMIT: "Terlalu banyak percobaan yang gagal. Silakan coba lagi dalam beberapa menit.",
    VERIFY_DOC_DETAILS: "Detail Dokumen",
    VERIFY_LABEL_COMPANY: "Perusahaan",
    VERIFY_LABEL_DATE: "Tanggal Terbit",
    VERIFY_LABEL_TOTAL: "Total Keseluruhan",
    VERIFY_BUTTON_DOWNLOAD_OFFICIAL: "Unduh PDF Resmi",
  }
}

export type ContentKey = keyof typeof SITE_CONTENT.en
