export const SITE_CONFIG = {
  brandName: "Nexus",
  companyName: "Nexus Integrated Distribution System",
  version: "v1.0.0",
  currencySymbol: "Rp",
  numberLocale: "id-ID",
  dateFormat: "dd/MM/yyyy",
  timeFormat: "HH:mm",
  assets: {
    loginImage: "/images/company-logo.jpg",
  }
}

export type Language = 'en' | 'id'

export const SITE_CONTENT = {
  en: {
    // Login Page
    LOGIN_TITLE: "NIDS System",
    LOGIN_SUBTITLE: "Enter your credentials to access the Nexus",
    LOGIN_ERROR_PENDING: "Your account is pending approval from the administrator.",
    LOGIN_ERROR_INVALID: "Invalid username or password.",
    LABEL_USERNAME: "Username",
    PLACEHOLDER_USERNAME: "admin",
    LABEL_PASSWORD: "Password",
    PLACEHOLDER_PASSWORD: "••••••••",
    BUTTON_LOGIN: "Sign In",
    LINK_SIGNUP: "Sign Up",
    TEXT_NO_ACCOUNT: "Don't have an account?",
    COPYRIGHT: "© 2026 Nexus Integrated Distribution System",

    // Signup Page
    SIGNUP_TITLE: "Create Account",
    SIGNUP_SUBTITLE: "Join the Nexus, approval required.",
    SIGNUP_SUCCESS_TITLE: "Registration Successful!",
    SIGNUP_SUCCESS_MSG: "Your account is pending boss approval.",
    LABEL_FULL_NAME: "Full Name",
    LABEL_EMAIL: "Email Address",
    LABEL_PHONE: "Phone Number",
    PLACEHOLDER_PHONE: "+62...",
    TOOLTIP_LANG: "Switch Language",
    BUTTON_SIGNUP: "Request Access",
    BUTTON_SIGNUP_LOADING: "Creating Account...",
    LINK_LOGIN: "Sign In",
    LINK_BACK_LOGIN: "Back to Login",
    LINK_RETURN_LOGIN: "Return to Login",
    TEXT_HAS_ACCOUNT: "Already have an account?",

    // Navigation / Titles
    MENU_DASHBOARD: "Dashboard",
    MENU_COMPANIES: "Companies",
    MENU_PRODUCTS: "Products",
    MENU_QUOTES: "Quotes",
    MENU_ORDERS: "Orders",
    MENU_SHIPMENTS: "Shipments",
    MENU_SETTINGS: "Settings",
    MENU_USERS: "Users",
    MENU_LOGOUT: "Logout",
    MENU_GROUP_MASTER: "Master Data",
    MENU_GROUP_REPORTS: "Reports",
    MENU_GROUP_SYSTEM: "System",
    MENU_SHOWCASE: "UI Showcase",

    TITLE_COMPANIES: "Companies",
    TITLE_PRODUCTS: "Products",
    TITLE_ADD_COMPANY: "Add Company",
    TITLE_EDIT_COMPANY: "Edit Company",
    TITLE_ADD_PRODUCT: "Add Product",
    TITLE_EDIT_PRODUCT: "Edit Product",

    DASHBOARD_TITLE: "Executive Dashboard",
    LABEL_TOTAL_REVENUE: "Total Revenue",
    LABEL_ACTIVE_COMPANIES: "Active Companies",
    LABEL_TOTAL_PRODUCTS: "Total Products",
    LABEL_FROM_LAST_MONTH: "from last month",
    LABEL_NEW_THIS_MONTH: "new this month",
    LABEL_PRODUCTS_IN_STOCK: "Oil grades in stock",

    // Labels
    LABEL_NAME: "Name",
    LABEL_COMPANY_NAME: "Company Name",
    LABEL_PRODUCT_NAME: "Product Name",
    LABEL_SKU: "SKU",
    LABEL_TYPE: "Type",
    LABEL_CATEGORY: "Category",
    LABEL_UNIT: "Unit",
    LABEL_PRICE: "Price",
    LABEL_BASE_PRICE: "Base Price",
    LABEL_ACTIONS: "Actions",
    LABEL_CONTACT_PERSON: "Contact Person",
    LABEL_CITY: "City",
    LABEL_ADDRESS: "Address",
    LABEL_OTHER_INFO: "Other Info",
    LABEL_TYPE_CUSTOMER: "Customer",
    LABEL_TYPE_SUPPLIER: "Supplier",
    LABEL_TYPE_TRANSPORTER: "Transporter",

    // General UI
    BUTTON_SAVE: "Save",
    BUTTON_CANCEL: "Cancel",
    BUTTON_ADD: "Add New",
    BUTTON_EDIT: "Edit",
    BUTTON_DELETE: "Delete",
    SEARCH_PLACEHOLDER: "Search...",
    LOADING: "Loading...",
    NO_DATA: "No data found.",
    LABEL_ALL: "All",

    // Status & Notifications
    MSG_STATUS_UPDATED: "Status Updated",
    MSG_UPDATE_FAILED: "Update Failed",
    MSG_SAVE_SUCCESS: "Saved Successfully",
    MSG_SAVE_FAILED: "Save Failed",
    MSG_DATA_FETCH_FAILED: "Data Fetch Failed",
    MSG_SESSION_EXPIRED: "Session Expired",
    MSG_RELOGIN: "Your session has expired. Please sign in again to continue.",
    LABEL_IS_ACTIVE: "Active",
    LABEL_IS_INACTIVE: "Inactive",
    MSG_PRODUCT_STATUS: "Product is now",
    MSG_COMPANY_STATUS: "Company is now",

    LABEL_LANGUAGE: "Language",
    LABEL_THEME: "Theme",
    LABEL_LIGHT: "Light",
    LABEL_DARK: "Dark",
    LABEL_SYSTEM: "System",

    // User Management
    TITLE_USER_MGMT: "User Management",
    TITLE_MANAGE_USER: "Manage User",
    LABEL_USER: "User",
    LABEL_PHONE_SHORT: "Phone",
    LABEL_STATUS: "Status",
    LABEL_ROLE: "Role",
    LABEL_APPROVED: "Approved",
    LABEL_PENDING: "Pending",
    LABEL_ACTIVE: "Active",
    LABEL_DEACTIVATED: "Deactivated",
    LABEL_MODULE: "Module",
    LABEL_GRANULAR_PERMS: "Granular Permissions",
    LABEL_ACC_APPROVAL: "Account Approval",
    DESC_ACC_APPROVAL: "Approve this user to give them access to the system.",
    BUTTON_APPROVE: "Approve User",
    BUTTON_REVOKE: "Revoke Approval",
    BUTTON_MANAGE: "Manage",
    MSG_ACCESS_DENIED: "Access Denied. Admin only.",

    // Validation Errors
    ERROR_INVALID_EMAIL: "Please enter a valid email address.",
    ERROR_PASSWORD_SHORT: "Password must be at least 6 characters.",
    ERROR_EMAIL_EXISTS: "This email address is already in use.",
    ERROR_USERNAME_EXISTS: "This username is already taken. Please try another one.",
    ERROR_PHONE_EXISTS: "This phone number is already registered.",
    ERROR_INFO_EXISTS: "An account with this information already exists.",
    ERROR_REG_RESTRICTED: "Registration is currently restricted. Please contact an admin.",
    ERROR_SUBMIT_FAILED: "Unable to submit request. Please check your information.",
    ERROR_UNEXPECTED: "An unexpected error occurred. Please try again.",
    ERROR_TIMEOUT: "Request timed out. Please check your connection and try again.",
    ERROR_VERIFY_STATUS: "Unable to verify account status.",

    // Additional Labels
    LABEL_NO_AUTH: "No Auth",
    LABEL_LAST_LOGIN: "Last Login",
    LABEL_USERNAME_FIELD: "Username",
    PLACEHOLDER_LOGIN_FALLBACK: "admin or email@example.com",

    // Reset Password / Forgot Password
    TITLE_RESET_PWD: "Reset Password",
    DESC_RESET_PWD: "Securely update your Nexus password.",
    TITLE_SETUP_ACC: "Account Setup",
    DESC_SETUP_ACC: "Complete your Nexus account activation.",
    LABEL_NEW_PASSWORD: "New Password",
    LABEL_CONFIRM_PASSWORD: "Confirm New Password",
    BUTTON_SET_NEW_PWD: "Set New Password",
    MSG_VERIFYING_TOKEN: "Verifying security token...",
    ERROR_EXPIRED_LINK: "This security link has expired. Please contact your administrator to revoke and re-approve your account access.",
    ERROR_INVALID_LINK: "Invalid security link. Please use the link provided in your email.",
    MSG_SECURITY_UPDATED: "Security Updated",
    MSG_RESET_LINK_SENT: "Security Link Dispatched",
    DESC_SECURITY_REDIRECT: "Your password has been set successfully. You are being redirected to the login page to sign in with your new credentials.",
    LINK_FORGOT_PWD: "Forgot password?",
    TITLE_FORGOT_PWD: "Reset Password",
    DESC_FORGOT_PWD: "Enter your email address and we'll send you a link to reset your password.",
    MSG_RESET_SENT: "If an account exists with this email, you will receive a password reset link shortly.",
    BUTTON_SEND_LINK: "Send Link",
    ERROR_PASSWORD_MISMATCH: "Passwords do not match. Please try again.",
  },
  id: {
    // Login Page
    LOGIN_TITLE: "Sistem NIDS",
    LOGIN_SUBTITLE: "Masukkan kredensial Anda untuk mengakses Nexus",
    LOGIN_ERROR_PENDING: "Akun Anda sedang menunggu persetujuan dari administrator.",
    LOGIN_ERROR_INVALID: "Nama pengguna atau kata sandi salah.",
    LABEL_USERNAME: "Nama Pengguna",
    PLACEHOLDER_USERNAME: "admin",
    LABEL_PASSWORD: "Kata Sandi",
    PLACEHOLDER_PASSWORD: "••••••••",
    BUTTON_LOGIN: "Masuk",
    LINK_SIGNUP: "Daftar",
    TEXT_NO_ACCOUNT: "Belum punya akun?",
    COPYRIGHT: "© 2026 Nexus Integrated Distribution System",

    // Signup Page
    SIGNUP_TITLE: "Buat Akun",
    SIGNUP_SUBTITLE: "Masuk ke Nexus. Perlu persetujuan bos.",
    SIGNUP_SUCCESS_TITLE: "Pendaftaran Berhasil!",
    SIGNUP_SUCCESS_MSG: "Akun Anda sedang menunggu persetujuan bos.",
    LABEL_FULL_NAME: "Nama Lengkap",
    LABEL_EMAIL: "Alamat Email",
    LABEL_PHONE: "Nomor Telepon",
    PLACEHOLDER_PHONE: "081xxx...",
    TOOLTIP_LANG: "Ganti Bahasa",
    BUTTON_SIGNUP: "Ajukan Akses",
    BUTTON_SIGNUP_LOADING: "Membuat Akun...",
    LINK_LOGIN: "Masuk",
    LINK_BACK_LOGIN: "Kembali ke Masuk",
    LINK_RETURN_LOGIN: "Kembali ke Masuk",
    TEXT_HAS_ACCOUNT: "Sudah punya akun?",

    // Navigation / Titles
    MENU_DASHBOARD: "Dasbord",
    MENU_COMPANIES: "Perusahaan",
    MENU_PRODUCTS: "Produk",
    MENU_QUOTES: "Penawaran",
    MENU_ORDERS: "Pesanan",
    MENU_SHIPMENTS: "Pengiriman",
    MENU_SETTINGS: "Pengaturan",
    MENU_USERS: "Pengguna",
    MENU_LOGOUT: "Keluar",
    MENU_GROUP_MASTER: "Data Master",
    MENU_GROUP_REPORTS: "Laporan",
    MENU_GROUP_SYSTEM: "Sistem",
    MENU_SHOWCASE: "Showcase UI",

    TITLE_COMPANIES: "Perusahaan",
    TITLE_PRODUCTS: "Produk",
    TITLE_ADD_COMPANY: "Tambah Perusahaan",
    TITLE_EDIT_COMPANY: "Ubah Perusahaan",
    TITLE_ADD_PRODUCT: "Tambah Produk",
    TITLE_EDIT_PRODUCT: "Ubah Produk",

    DASHBOARD_TITLE: "Dasbor Eksekutif",
    LABEL_TOTAL_REVENUE: "Total Pendapatan",
    LABEL_ACTIVE_COMPANIES: "Perusahaan Aktif",
    LABEL_TOTAL_PRODUCTS: "Total Produk",
    LABEL_FROM_LAST_MONTH: "dari bulan lalu",
    LABEL_NEW_THIS_MONTH: "baru bulan ini",
    LABEL_PRODUCTS_IN_STOCK: "Varian oli tersedia",

    // Labels
    LABEL_NAME: "Nama",
    LABEL_COMPANY_NAME: "Nama Perusahaan",
    LABEL_PRODUCT_NAME: "Nama Produk",
    LABEL_SKU: "SKU",
    LABEL_TYPE: "Tipe",
    LABEL_CATEGORY: "Kategori",
    LABEL_UNIT: "Satuan",
    LABEL_PRICE: "Harga",
    LABEL_BASE_PRICE: "Harga Dasar",
    LABEL_ACTIONS: "Aksi",
    LABEL_CONTACT_PERSON: "Kontak Person",
    LABEL_CITY: "Kota",
    LABEL_ADDRESS: "Alamat",
    LABEL_OTHER_INFO: "Info Lainnya",
    LABEL_TYPE_CUSTOMER: "Pelanggan",
    LABEL_TYPE_SUPPLIER: "Pemasok",
    LABEL_TYPE_TRANSPORTER: "Transporter",

    // General UI
    BUTTON_SAVE: "Simpan",
    BUTTON_CANCEL: "Batal",
    BUTTON_ADD: "Tambah Baru",
    BUTTON_EDIT: "Ubah",
    BUTTON_DELETE: "Hapus",
    SEARCH_PLACEHOLDER: "Cari...",
    LOADING: "Memuat...",
    NO_DATA: "Data tidak ditemukan.",
    LABEL_ALL: "Semua",

    // Status & Notifications
    MSG_STATUS_UPDATED: "Status Diperbarui",
    MSG_UPDATE_FAILED: "Pembaruan Gagal",
    MSG_SAVE_SUCCESS: "Berhasil Disimpan",
    MSG_SAVE_FAILED: "Penyimpanan Gagal",
    MSG_DATA_FETCH_FAILED: "Gagal Mengambil Data",
    MSG_SESSION_EXPIRED: "Sesi Berakhir",
    MSG_RELOGIN: "Sesi Anda telah berakhir. Silakan masuk kembali untuk melanjutkan.",
    LABEL_IS_ACTIVE: "Aktif",
    LABEL_IS_INACTIVE: "Nonaktif",
    MSG_PRODUCT_STATUS: "Produk sekarang",
    MSG_COMPANY_STATUS: "Perusahaan sekarang",

    LABEL_LANGUAGE: "Bahasa",
    LABEL_THEME: "Tema",
    LABEL_LIGHT: "Terang",
    LABEL_DARK: "Gelap",
    LABEL_SYSTEM: "Sistem",

    // User Management
    TITLE_USER_MGMT: "Manajemen Pengguna",
    TITLE_MANAGE_USER: "Kelola Pengguna",
    LABEL_USER: "Pengguna",
    LABEL_PHONE_SHORT: "Telepon",
    LABEL_STATUS: "Status",
    LABEL_ROLE: "Peran",
    LABEL_APPROVED: "Disetujui",
    LABEL_PENDING: "Tertunda",
    LABEL_ACTIVE: "Aktif",
    LABEL_DEACTIVATED: "Dinonaktifkan",
    LABEL_MODULE: "Modul",
    LABEL_GRANULAR_PERMS: "Izin Granular",
    LABEL_ACC_APPROVAL: "Persetujuan Akun",
    DESC_ACC_APPROVAL: "Setujui pengguna ini untuk memberi mereka akses ke sistem.",
    BUTTON_APPROVE: "Setujui Pengguna",
    BUTTON_REVOKE: "Cabut Persetujuan",
    BUTTON_MANAGE: "Kelola",
    MSG_ACCESS_DENIED: "Akses Ditolak. Khusus Admin.",

    // Validation Errors
    ERROR_INVALID_EMAIL: "Silakan masukkan alamat email yang valid.",
    ERROR_PASSWORD_SHORT: "Kata sandi harus minimal 6 karakter.",
    ERROR_EMAIL_EXISTS: "Alamat email ini sudah digunakan.",
    ERROR_USERNAME_EXISTS: "Nama pengguna ini sudah diambil. Silakan coba yang lain.",
    ERROR_PHONE_EXISTS: "Nomor telepon ini sudah terdaftar.",
    ERROR_INFO_EXISTS: "Akun dengan informasi ini sudah ada.",
    ERROR_REG_RESTRICTED: "Pendaftaran saat ini dibatasi. Silakan hubungi admin.",
    ERROR_SUBMIT_FAILED: "Tidak dapat mengajukan permintaan. Silakan periksa informasi Anda.",
    ERROR_UNEXPECTED: "Terjadi kesalahan yang tidak terduga. Silakan coba lagi.",
    ERROR_TIMEOUT: "Permintaan kehabisan waktu. Silakan periksa koneksi Anda dan coba lagi.",
    ERROR_VERIFY_STATUS: "Tidak dapat memverifikasi status akun.",

    // Additional Labels
    LABEL_NO_AUTH: "Belum Ada Akun",
    LABEL_LAST_LOGIN: "Login Terakhir",
    LABEL_USERNAME_FIELD: "Nama Pengguna",
    PLACEHOLDER_LOGIN_FALLBACK: "admin atau email@example.com",

    // Reset Password / Forgot Password
    TITLE_RESET_PWD: "Atur Ulang Kata Sandi",
    DESC_RESET_PWD: "Perbarui kata sandi Nexus Anda dengan aman.",
    TITLE_SETUP_ACC: "Pengaturan Akun",
    DESC_SETUP_ACC: "Selesaikan aktivasi akun Nexus Anda.",
    LABEL_NEW_PASSWORD: "Kata Sandi Baru",
    LABEL_CONFIRM_PASSWORD: "Konfirmasi Kata Sandi Baru",
    BUTTON_SET_NEW_PWD: "Atur Kata Sandi Baru",
    MSG_VERIFYING_TOKEN: "Memverifikasi token keamanan...",
    ERROR_EXPIRED_LINK: "Tautan keamanan ini telah kedaluwarsa. Silakan hubungi administrator Anda.",
    ERROR_INVALID_LINK: "Tautan keamanan tidak valid. Silakan gunakan tautan yang disediakan di email Anda.",
    MSG_SECURITY_UPDATED: "Keamanan Diperbarui",
    MSG_RESET_LINK_SENT: "Tautan Keamanan Dikirim",
    DESC_SECURITY_REDIRECT: "Kata sandi Anda telah berhasil diatur. Anda sedang dialihkan ke halaman login.",
    LINK_FORGOT_PWD: "Lupa kata sandi?",
    TITLE_FORGOT_PWD: "Atur Ulang Kata Sandi",
    DESC_FORGOT_PWD: "Masukkan alamat email Anda dan kami akan mengirimkan tautan untuk mengatur ulang kata sandi Anda.",
    MSG_RESET_SENT: "Jika akun dengan email ini ada, Anda akan segera menerima tautan atur ulang kata sandi.",
    BUTTON_SEND_LINK: "Kirim Tautan",
    ERROR_PASSWORD_MISMATCH: "Kata sandi tidak cocok. Silakan coba lagi.",
  }
}

export type ContentKey = keyof typeof SITE_CONTENT.en
